spring.application.name=nexus

spring.datasource.url=jdbc:mysql://localhost:3306/nexus
spring.datasource.username=root
spring.datasource.password=Smydhrj30$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
jwt.secret=MyVerySecretKeyForNexusBackendProject2026MyVerySecretKey
jwt.expiration=3600000